---
- name: Redemarrer machine Windows
  hosts: windows
  gather_facts: no

  tasks:
    - name: Reboot Windows
      ansible.windows.win_reboot:
        msg: "Redemarrage déclenché par Ansible"
        pre_reboot_delay: 0
        post_reboot_delay: 30
        reboot_timeout: 600
